[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_source = '''
    let g:airline-powerline-fonts = 1
'''
